FROM node:18-alpine AS build
WORKDIR /app
COPY ./mcp_client/package*.json ./
COPY .env .
RUN npm install
COPY ./mcp_client ./
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]